/** Machine-readable codes for clients (i18n keys: auth.errors.<CODE>). */
export const AuthErrorCode = {
    USER_NOT_FOUND: 'AUTH_USER_NOT_FOUND',
    INVALID_CREDENTIALS: 'AUTH_INVALID_CREDENTIALS',
    LOGIN_RATE_LIMITED: 'AUTH_LOGIN_RATE_LIMITED',
    EMAIL_ALREADY_EXISTS: 'AUTH_EMAIL_ALREADY_EXISTS',
    REGISTRATION_FAILED: 'AUTH_REGISTRATION_FAILED',
    GOOGLE_INVALID_TOKEN: 'AUTH_GOOGLE_INVALID_TOKEN',
    GOOGLE_EMAIL_NOT_IN_TOKEN: 'AUTH_GOOGLE_EMAIL_NOT_IN_TOKEN',
    GOOGLE_PROVIDER_MISMATCH: 'AUTH_GOOGLE_PROVIDER_MISMATCH',
    GOOGLE_REGISTRATION_FAILED: 'AUTH_GOOGLE_REGISTRATION_FAILED',
} as const;

export type AuthErrorCodeValue = (typeof AuthErrorCode)[keyof typeof AuthErrorCode];
